language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- bundle exec rails s -d
- sleep 3
deploy:
  provider: heroku
  api_key:
    secure: JVoDLYn+gJhoQmM0xkvUcDNogmiZdxhoyGYNFE78NtCt+fMPKeVZijs3enYsZk/NTCVdZUuGGi2Zpsu0duZYM8ZJQbtLk056Wv4lm9QnCdNPnSffFuNQk0Q9ZL6+xAaXfEwma+SbMLneYP2bvAeExrM7d13p0a/wYs3FdXMKBEw=
  app: Will-Code-For-Booze
  on:
    repo: Tyhjis/Will-Code-For-Booze
